sudo: required
services:
  docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_254df65517a8_key -iv $encrypted_254df65517a8_iv -in service-account-new.json.enc -out service-account-new.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account-new.json
  - gcloud config set project multi-k8s-281214 # Run this,
  - gcloud config set compute/zone asia-south1-b # this
  - gcloud container clusters get-credentials multi-cluster # and this on cloud console to setup kubectl
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t bhargavsnv/react-test -f ./client/Dockerfile.dev ./client

script:
  docker run -e CI=true bhargavsnv/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
