sudo: required
services:
  docker

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_install:
  - openssl aes-256-cbc -K $encrypted_254df65517a8_key -iv $encrypted_254df65517a8_iv -in service-account-new.json.enc -out service-account-new.json -d
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud auth activate-service-account --key-file service-account-new.json
  - gcloud config set project multi-k8s-281214
  - gcloud config set compute/zone asia-south1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t bhargavsnv/react-test -f ./client/Dockerfile.dev ./client

script:
  docker run -e CI=true bhargavsnv/react-test npm run test
